image:
  file: Dockerfile
checkoutLocation: "shopware"
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
  - name: Start Apache
    command: >
        apachectl start;
  - name: Start MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld &
        sleep 5;
        echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'gitpod'; CREATE DATABASE shopware;" | mysql -uroot;
  - name: Shopware 6
    command: >
        sleep 10;
        cd $GITPOD_REPO_ROOT;
        cd src;
        composer install;
        mkdir -p var/log;
        mkdir -p var/cache;
        bin/setup;