image:
  file: Dockerfile
checkoutLocation: "shopware"
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
 - name: Terminal
   command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
 - name: Apache
   command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.lo
 - name: Shopware 6
   command: >
        sleep 10;
        cd $GITPOD_REPO_ROOT;
        cd src;
        mkdir -p var/log;
        mkdir -p var/cache;
        bin/setup;