image:
  file: .gitpod.dockerfile
checkoutLocation: "shopware"
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
tasks:
 - name: Apache
   command: >
    apachectl start;
 - name: Shopware 6
   command: >
        sleep 10;
        cd $GITPOD_REPO_ROOT;
        cd src;
        mkdir -p var/log;
        mkdir -p var/cache;
        bin/setup;